[package]
name = "traffic_light"
version = "0.1.0"
authors = ["NAV <2907163991@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
